### ISSUE TITLE
Does not write files with relative paths

### ISSUE THREAD

**Issue by ik0r** [gajus/write-file-webpack-plugin#15]
I just used the latest version. this plugin can successfully write html files.

But I found it can't write files to correct place.

In my html-webpack-plugin, I config it write files to `../index.html`.

If I run `webpack`, files are wrote correctly. But if I run `webpack-dev-server`, files are wrote to `./index.html`.

screenshot: 
![image](https://cloud.githubusercontent.com/assets/2631733/12527443/26e7de36-c1b6-11e5-8797-2c8eef418cd6.png)

**EDIT**: my project demo is https://github.com/Treri/webpack-example

**Comment by gajus** [comment]
@Treri Fixed in `write-file-webpack-plugin@3.1.1`. Please confirm.

**Comment by ik0r** [comment]
@gajus Solved! Thanks very much :+1:
