### ISSUE TITLE
Ensure output path exists and write all handled files 

### ISSUE THREAD

**Issue by majodev** [gajus/write-file-webpack-plugin#2]
Hi,

Your plugin currently throws if the specified output directory was not created before (or cleaned via another plugin at the start) and does not handle assets that were not part of a chunk. I think @sretlawd fixes this quite nicely in his fork, you might wanna take a look at it and merge back...

see: https://github.com/sretlawd/write-file-webpack-plugin/commit/0ccdacdc0612f0f362c151cef88685292ee81093

Anyways, Thank you for this plugin. :+1:

**Comment by gajus** [comment]
I will happily accept a PR.

**Comment by gajus** [comment]
@chrisblossom, @majodev, @sretlawd please see if v2 solves the problem.

**Comment by chrisblossom** [comment]
@gajus I am actually not using the webpack-dev-server package. Can this devServer.outputPath change be optional?

Also, the option to only write specific extensions, specifically only .css, was removed from this PR which was in mine. Would you accept a pull request with this functionality built on 2.0?

EDIT: FYI, I am using https://github.com/erikras/react-redux-universal-hot-example for a boilerplate.

**Comment by gajus** [comment]
> EDIT: FYI, I am using https://github.com/erikras/react-redux-universal-hot-example for a boilerplate.

Does this not have the issue described here? https://github.com/gajus/write-file-webpack-plugin/issues/1

**Comment by gajus** [comment]
> Also, the option to only write specific extensions, specifically only .css, was removed from this PR which was in mine. Would you accept a pull request with this functionality built on 2.0?

Please open a new issue. The reason it was "removed" is because it has not been discussed as a separate issue.

**Comment by chrisblossom** [comment]
#1 does not appear to be an issue when not using webpack-dev-server.

``` javascript
console.log(compiler.options.output);

{ path: '/Users/chris/github/website/static/dist',
  filename: '[name]-[hash].js',
  chunkFilename: '[name]-[chunkhash].js',
  publicPath: 'http://localhost:3001/dist/',
  libraryTarget: 'var',
  sourceMapFilename: '[file].map[query]',
  hotUpdateChunkFilename: '[id].[hash].hot-update.js',
  hotUpdateMainFilename: '[hash].hot-update.json',
  crossOriginLoading: false,
  hashFunction: 'md5',
  hashDigest: 'hex',
  hashDigestLength: 20,
  sourcePrefix: '\t',
  devtoolLineToLine: false }
```

**Comment by gajus** [comment]
I think that having `devServer.outputPath` does not hurt anyone and it makes the configuration work regardless of the execution context. I would not want my instructions to produce different results depending on the implementation of the program.

Therefore, unless someone gives a good reason not to, I will be keeping the `devServer.outputPath` solution.

The ideal solution would be contributing a fix to the https://github.com/webpack/webpack-dev-server.

**Comment by chrisblossom** [comment]
When adding "devServer: {outputPath: assetsPath}, " to my config I am getting the following error:

```
[0] Error: no such file or directory
[0]     at MemoryFileSystem.readFileSync (/Users/chris/github/website/node_modules/memory-fs/lib/MemoryFileSystem.js:114:10)
[0]     at /Users/chris/github/website/node_modules/write-file-webpack-plugin/dist/index.js:77:52
[0]     at arrayEach (/Users/chris/github/website/node_modules/lodash/internal/arrayEach.js:15:9)
[0]     at /Users/chris/github/website/node_modules/lodash/internal/createForEach.js:15:9
[0]     at Compiler.<anonymous> (/Users/chris/github/website/node_modules/write-file-webpack-plugin/dist/index.js:71:31)
[0]     at Compiler.applyPlugins (/Users/chris/github/website/node_modules/tapable/lib/Tapable.js:26:37)
[0]     at Watching._done (/Users/chris/github/website/node_modules/webpack/lib/Compiler.js:78:17)
[0]     at Watching.<anonymous> (/Users/chris/github/website/node_modules/webpack/lib/Compiler.js:61:18)
[0]     at Compiler.emitRecords (/Users/chris/github/website/node_modules/webpack/lib/Compiler.js:282:37)
[0]     at Watching.<anonymous> (/Users/chris/github/website/node_modules/webpack/lib/Compiler.js:58:19)
```

``` javascript
console.log(outputPath);

[0] /Users/chris/github/website/static/dist
```

**Comment by gajus** [comment]
What is the name of `bundleFileName`?

**Comment by gajus** [comment]
Does the issue persist if you replace

``` js
bundleFilePath = path.join('/', bundleFileName);
```

with

``` js
bundleFilePath = path.join(outputPath, bundleFileName);
```

?

**Comment by gajus** [comment]
I have just pushed version 2.1.1 that implements the earlier suggestion.

**Comment by chrisblossom** [comment]
Just a thought to make it less opinionated/remove devServer requirement:

``` javascript
if (compiler.options.devServer && (compiler.options.devServer.outputPath !== compiler.options.output.path)) {
    throw new Error('output.path and devServer.outputPath must be equal.');
}
outputPath = compiler.options.output.path;
```

Readme could say something along the lines of "If using webpack-dev-server, devServer.outputPath must equal output.path."

**Comment by chrisblossom** [comment]
Confirmed that 2.1.1 https://github.com/gajus/write-file-webpack-plugin/commit/4d2a3e512c5f78aead3e08ab2a9b295c906e0fcc fixed the error I was getting.

**Comment by gajus** [comment]
> Confirmed that 2.1.1 4d2a3e5 fixed the error I was getting.

Thank you

**Comment by gajus** [comment]
> Just a thought to make it less opinionated/remove devServer requirement:

Please copy-paste you have written and open a separate issue.
