### ISSUE TITLE
Outputting extra files to build

### ISSUE THREAD

**Issue by mikeLspohn** [gajus/write-file-webpack-plugin#23]
I'm not sure if it's from this plugin, or `webpack-dev-server` or the `react-hot-loader` but I finally got my build working using this plugin, but after it hot reloads I get my expected `build.js` but it also outputs a `0.90jkjijg409.hot-update.js` and a similar `.json` file into the folder where my bundle.js is output.

Here's the webpack config I'm using:

```
var webpack = require('webpack')
var path = require('path')
var WriteFilePlugin = require('write-file-webpack-plugin')

module.exports = {
  context: __dirname + '/app/assets/javascripts',
  entry: {
    App: [
      'webpack-dev-server/client?http://localhost:8080/',
      'webpack/hot/only-dev-server',
      path.resolve(__dirname, 'app/assets/source/index.js')
    ]
  },
  output: {
    path: path.resolve(__dirname, 'app/assets/javascripts'),
    publicPath: 'http://localhost:8080',
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      { test: /\.js$/,
        loaders: ["react-hot", "babel"],
        include: path.resolve(__dirname, 'app/assets/source')
      }
    ]
  },
  devtool: 'source-map',
  devServer: {
    outputPath: path.resolve(__dirname, 'app/assets/javascripts')
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new WriteFilePlugin
  ]
})
```

Any idea why this would happen or how to prevent it if it's expected?

**Comment by gajus** [comment]
You can use `test` option to ignore `.hot` files.

See https://github.com/gajus/write-file-webpack-plugin#api

**Comment by mikeLspohn** [comment]
Thank you, I didn't notice that option. I'm having trouble though figuring out how to ignore the files since it needs a regex that is looking for it (hot-update) to NOT be there, I'm not sure how to write it. And I can't just do  `/\.js$/` because the files still end in js, so that doesn't work.

**Comment by gajus** [comment]
Thats a question outside the scope of this module.

**Comment by mikeLspohn** [comment]
Agreed on that point. I'm just wondering if this is normal behavior and if this usually happens when using the plugin. If so I would imagine most people wouldn't want that to be the case, so it might be mentioned in the docs. But I guess it may not have anything to do with this plugin. Thanks for the help.

**Comment by gajus** [comment]
It is an open source project. Contributions to documentation are most welcome.

**Comment by DotCoyote** [comment]
Works:

`new WriteFilePlugin({test: /^(?!.+(?:hot-update.(js|json))).+$/})`

Thanks to @martinherweg
