### ISSUE TITLE
Webpack 2

### ISSUE THREAD

**Issue by dsebastien** [gajus/write-file-webpack-plugin#30]
Hello,

I'm busy migrating to Webpack 2 and I'm wondering if this plugin has already been tested with it?
We followed your documentation and added the outputPath property to our webpack-dev-server config but it now fails because it's not part of the schema of Webpack 2.

**Comment by odensc** [comment]
I did this as a temporary hack until the plugin is updated:

```js
const base = {
	devServer: {
		hot: true,
		contentBase: "./output"
	},
	// [...] other config
};

Object.defineProperty(base.devServer, "outputPath", {
        // make it non-enumerable so webpack can't complain about the schema
	enumerable: false,
        // change to your output path
	value: "./output"
});

module.exports = base;
```

**Comment by gajus** [comment]
> I did this as a temporary hack until the plugin is updated:

If this plugin is broken with webpack 2, I'd happily accept a PR for a fix.

**Comment by toxic-johann** [comment]
i comme across this problem too.it failed to find out the output path i config. i try @thesbros method. and worte it in this way
```
const base = {
          contentBase: 'www/static',
          path: pathPosix.resolve('./www/static'),
          proxy: {
            '*': 'http://localhost:8360'
            // '*': 'http://speech.baomitu.com'
          },
          publicPath: '/static/',
          clientLogLevel: 'none'
        }
        Object.defineProperty(base, 'outputPath', {
          // make it non-enumerable so webpack can't complain about the schema
          enumerable: false,
          // change to your output path
          value: pathPosix.resolve('./www/static')
        })
        const server = new WebpackDevServer(compiler, base)
        server.listen('8888', 'dev.speech.baomitu.com', function () {})
```
and it still fail.
r there any good way to handle it?

**Comment by toxic-johann** [comment]
i figure out the why i cause that problem.it's caused by file-loader, not this plugin fault.Thanks a lot

**Comment by odensc** [comment]
@gajus I submitted a PR.
