### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by nkzawa** [gajus/write-file-webpack-plugin#32]
I wonder why this library supports only `>=5`. I think plugins should support what `webpack` does as much as possible. 

I want Node 4 support for our library ([next.js](https://github.com/zeit/next.js)) which only this module has the problem.

**Comment by nakedible** [comment]
I concur wholeheartedly. Node 4 is still in active LTS, and for example AWS Lambda does not support anything newer.

**Comment by gajus** [comment]
Please use the thumbs up on the issue to cast vote for a feature. I am using these to prioritise issues across many repositories.

**Comment by arianrhodsandlot** [comment]
Any good news here?  Are there any codes using features in Node.js v5 which v4 doesn't have?

**Comment by chrisblossom** [comment]
Node v4 support has been added as of #53. This issue can be closed.
