### ISSUE TITLE
Specify extensions to write

### ISSUE THREAD

**Issue by chrisblossom** [gajus/write-file-webpack-plugin#4]
Would be great to be able to specify which extensions are written to disk instead of writing all.

Here is my related pull request: #3 

If you would like me to remake it for 2.0 I am more than happy to.

**Comment by gajus** [comment]
I will add `test` property (equivalent to the `module.loaders` `test` property, https://webpack.github.io/docs/configuration.html#module-loaders).

Do you agree with such implementation?

**Comment by chrisblossom** [comment]
Yes, I think that would work great.

**Comment by gajus** [comment]
@chrisblossom Released in 2.1.0. See documentation https://github.com/gajus/write-file-webpack-plugin#api.

**Comment by chrisblossom** [comment]
@gajus thank you!
