### ISSUE TITLE
Remove devServer.outputPath requirement

### ISSUE THREAD

**Issue by chrisblossom** [gajus/write-file-webpack-plugin#5]
Just a thought to make it less opinionated/remove devServer requirement when not using webpack-dev-server:

``` javascript
if (!compiler.options.output.path) {
    throw new Error('output.path is not defined.');
}

if (compiler.options.devServer && (compiler.options.devServer.outputPath !== compiler.options.output.path)) {
    throw new Error('output.path and devServer.outputPath must be equal.');
}

outputPath = compiler.options.output.path;
```

Readme could say something along the lines of "If using webpack-dev-server, devServer.outputPath must equal output.path."

**Comment by gajus** [comment]
First I will see if I can make `webpack-dev-server` change the behaviour on their end (https://github.com/webpack/webpack-dev-server/issues/337). Will come back to this in about a week.

**Comment by gajus** [comment]
@chrisblossom v3.1.7 published.

**Comment by chrisblossom** [comment]
@gajus thank you!

**Comment by ik0r** [comment]
@gajus webpack-dev-server still overwrite output.path, so this plugin get error output.path when use `compiler.options.output.path`

And when I use this plugin in windows, all files are wrote to incorrect place

because `path.sep` in windows is `\`, so `compiler.options.output.path` is used incorrectly

**Comment by gajus** [comment]
> @gajus webpack-dev-server still overwrite output.path, so this plugin get error output.path when use compiler.options.output.path

Have you read the usage docs?

https://github.com/gajus/write-file-webpack-plugin#usage

**Comment by gajus** [comment]
> because path.sep in windows is \, so compiler.options.output.path is used incorrectly

I am not familiar with windows. Can you submit a PR addressing the issue?

**Comment by ik0r** [comment]
OK. I will make a PR to solve this problem.
