### ISSUE TITLE
Support `webpack@4`

### ISSUE THREAD

**Issue by alexander-akait** [gajus/write-file-webpack-plugin#50]
https://github.com/webpack/webpack/releases/tag/v4.0.0-alpha.0

**Comment by brillout** [comment]
With webpack 4 I get 

> DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

@gajus Do you maintain this plugin?

(Thanks for this awesome plugin btw.)

**Comment by alexander-akait** [comment]
@gajus Also if you don't have time to maintenance this, maybe we can migrate this to `webpack-contrib`?

**Comment by radut** [comment]
any news on WebPack v4 compatibility ?

**Comment by alexander-akait** [comment]
@radut you don't need this plugin anymore, https://github.com/webpack/webpack-dev-middleware#writetodisk

**Comment by tech4him1** [comment]
@evilebottnawi Is there a way to use the `writeToDisk` option directly through webpack-dev-server, or does the middleware need to be used directly?

**Comment by radut** [comment]
I need a simple solution to add to WDS,
select which file pattern to always write on disk..
not to reinvent the wheel with new middleware :-?

**Comment by bebraw** [comment]
@tech4him1 See [webpack-serve](https://www.npmjs.com/package/webpack-serve). It's a light alternative to WDS and you can set the flag there. After doing that, you don't need this plugin anymore.

**Comment by mrukas** [comment]
This plugin works perfectly fine with webpack 4.5.0. I also get the DeprecationWarning, but the plugin still does what it's intended to do.

**Comment by alexander-akait** [comment]
@gajus can we add note in readmy about support `webpack-dev-middleware` feature to avoid questions

**Comment by gajus** [comment]
> @gajus can we add note in readmy about support webpack-dev-middleware feature to avoid questions

PR welcome.

**Comment by sikhote** [comment]
@tech4him1 https://github.com/webpack/webpack-dev-server/issues/1357
