### ISSUE TITLE
New vulnerability on moment

### ISSUE THREAD

**Issue by luisherranz** [gajus/write-file-webpack-plugin#52]
It looks like there is a new vulnerability on moment 2.19.3:
![screen shot 2018-03-06 at 10 21 09](https://user-images.githubusercontent.com/3305402/37024049-20a3c7be-2128-11e8-9d2c-7bb54e687b85.png)

**Comment by chrisblossom** [comment]
``moment`` was updated to the latest version as of #53. This issue can be closed.

**Comment by luisherranz** [comment]
Thanks!
