### ISSUE TITLE
CSS files not written to disk using mini-css-extract-plugin in dev mode

### ISSUE THREAD

**Issue by Luckyfella73** [gajus/write-file-webpack-plugin#57]
Hello,

I'm on my way to upgrade my bundler configuration to webpack 4.6. Like recommended I try to implement the _**mini-css-extract-plugin**_ instead of **_extract-text-webpack-plugin_**. When performing a build all my assets are written to disk but using webpack-dev-server only my javascript files are written to disk - all CSS is injected. Any ideas what could cause this problem?

Having installed:
webpack 4.6.0
write-file-webpack-plugin 4.2.0
mini-css-extract-plugin 0.4.0

**Comment by boraturant** [comment]
Same here

**Comment by emendelski** [comment]
👍

**Comment by emendelski** [comment]
Ok, I found a way to resolve this. And this is not the problem with `write-file-webpack-plugin`.
@Luckyfella73, @boraturant - proper configuration below:

````js
test: /\.scss$/,
use: [ 
  MiniCssExtractPlugin.loader,
  {
    loader: 'css-loader', 
  },
  ...
]
````

You should remove `style-loader` and for sure add `MiniCssExtractPlugin.loader`.
CSS files will be then properly written.

**Comment by Luckyfella73** [comment]
@emendelski thank you so much! Today I found the time to edit my config file and after a while I got it to work. So, finally no more extract-text-webpack-plugin :)
