### ISSUE TITLE
Add support for `ignore` regex?

### ISSUE THREAD

**Issue by mrlubos** [gajus/write-file-webpack-plugin#59]
It's notoriously difficult to invert regex match (see [here](https://stackoverflow.com/questions/164414/how-to-inverse-match-with-regex), [here](https://stackoverflow.com/questions/957379/invert-match-with-regexp), or [here](https://stackoverflow.com/questions/1538512/how-can-i-invert-a-regular-expression-in-javascript)) so it would be useful to have an option to exclude matched files. What do you think?

EDIT: I would also suggest splitting regex tests into `include` and `exclude` similarly to Webpack loader configuration objects, but as this would be a breaking change we might stick to adding only `ignore` for now.

**Comment by mrlubos** [comment]
I see now that I could pass a function to `test`, but why are you not bumping up the project version? Using `yarn add -D write-file-webpack-plugin@next` goes only up to 4.2.0 which does not have this feature yet.

**Comment by gajus** [comment]
New version published.

**Comment by mrlubos** [comment]
@gajus Thanks!
