### ISSUE TITLE
Document require().default 

### ISSUE THREAD

**Issue by chrisblossom** [gajus/write-file-webpack-plugin#6]
Webpack configs often written using require() instead of import and because of Babel@6 you must append .default to require(). I think it would be a good idea to document this or add [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports) to the build step so it isn't required.

``` javascript
var WriteFilePlugin = require('write-file-webpack-plugin').default;
```

**Comment by barroudjo** [comment]
+1

**Comment by gajus** [comment]
Reverted to the Babel 5 behaviour, i.e.,

``` js
var WriteFilePlugin;

WriteFilePlugin = require('write-file-webpack-plugin');
```

is sufficient.
