### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by atrauzzi** [gajus/write-file-webpack-plugin#67]
Would love to see this package incorporate typescript typings!

**Comment by gajus** [comment]
I don't use TS.

**Comment by atrauzzi** [comment]
Okay -- but others do, and your library [is suggested in webpack documentation](https://webpack.js.org/plugins/copy-webpack-plugin/).  Probably wouldn't hurt to broaden the reach of the library at that rate.

_(You don't even have to be using TypeScript to benefit from typings.  Visual Studio code will read them during regular JS development.  Other languages are even leveraging definition files as a header format.)_

**Comment by gajus** [comment]
> You don't even have to be using TypeScript to benefit from typings. Visual Studio code will read them during regular JS development. Other languages are even leveraging definition files as a header format.

Yes, but I will need to support it. Meaning that every time I make changes to the API, I will need someone's help to test TS.

Either way, there is a public TS types repository exactly for this reason.

**Comment by atrauzzi** [comment]
Yup, but always better if it's incorporated as part of the library itself as you (or other maintainers) are the authority on usage.

Strictly speaking for the sake of this library, I can't imagine its public surface changes that often, so really -- is that a practical concern?

**Comment by gajus** [comment]
> Strictly speaking for the sake of this library, I can't imagine its public surface changes that often, so really -- is that a practical concern?

If this was the only library I was maintaining, probably not. But it isn't.

**Comment by atrauzzi** [comment]
I don't use the other libraries. 😜

**Comment by tjx666** [comment]
> Okay -- but others do, and your library [is suggested in webpack documentation](https://webpack.js.org/plugins/copy-webpack-plugin/). Probably wouldn't hurt to broaden the reach of the library at that rate.
> 
> _(You don't even have to be using TypeScript to benefit from typings. Visual Studio code will read them during regular JS development. Other languages are even leveraging definition files as a header format.)_

This plugin had been removed from the webpack documention suggested plugin list...

**Comment by gajus** [comment]
> This plugin had been removed from the webpack documention suggested plugin list...

It is still there.

**Comment by nhardy** [comment]
FYI [`@types/write-file-webpack-plugin`](https://www.npmjs.com/package/@types/write-file-webpack-plugin) is now available on npm.
